run:
  concurrency: 8
  timeout: 5m
  build-tags:
    - integration
  modules-download-mode: readonly
  go: '1.17'
output:
  format: tab:lint.txt
  print-issued-lines: false
  uniq-by-line: false
  sort-results: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofumpt
    - gci
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  disable:
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
linters-settings:
  gci:
    sections:
      - standard # Standard lib
      - default # External dependencies
      - prefix(github.com/maypok86/otter) # Internal packages
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
  nakedret:
    max-func-lines: 1
  revive:
    rules:
      - name: empty-block
        disabled: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
