// Copyright (c) 2024 Alexey Mayshev and contributors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func printManager(dir string) error {
	const nodeManager = `// Code generated by NodeGenerator. DO NOT EDIT.

// Package node is a generated generator package.
package node

import (
	"reflect"
	"strings"
	"unsafe"
)

const (
	InWindowQueue uint8 = iota
	InMainProbationQueue
	InMainProtectedQueue
)

const (
	aliveState uint32 = iota
	retiredState
	deadState
)

// Node is a cache entry.
type Node[K comparable, V any] interface {
	// Key returns the key.
	Key() K
	// Value returns the value.
	Value() V
	// SetValue atomically replaces the value (used for in-place updates).
	SetValue(v V)
	// CanSetValue reports whether the value can be replaced in place with SetValue without a
	// concurrent reader observing a torn value: it is kept in one atomic word, or behind a pointer.
	CanSetValue() bool
	// AsPointer returns the node as a pointer.
	AsPointer() unsafe.Pointer
	// Prev returns the previous node in the eviction policy.
	Prev() Node[K, V]
	// SetPrev sets the previous node in the eviction policy.
	SetPrev(v Node[K, V])
	// Next returns the next node in the eviction policy.
	Next() Node[K, V]
	// SetNext sets the next node in the eviction policy.
	SetNext(v Node[K, V])
	// PrevExp returns the previous node in the expiration policy.
	PrevExp() Node[K, V]
	// SetPrevExp sets the previous node in the expiration policy.
	SetPrevExp(v Node[K, V])
	// NextExp returns the next node in the expiration policy.
	NextExp() Node[K, V]
	// SetNextExp sets the next node in the expiration policy.
	SetNextExp(v Node[K, V])
	// HasExpired returns true if node has expired.
	HasExpired(now int64) bool
	// ExpiresAt returns the expiration time.
	ExpiresAt() int64
	// CASExpiresAt executes the compare-and-swap operation for expiresAt.
	CASExpiresAt(old, new int64) bool
	// SetExpiresAt sets the expiration time.
	SetExpiresAt(new int64)
	// RefreshableAt returns the refresh time.
	RefreshableAt() int64
	// CASRefreshableAt executes the compare-and-swap operation for refreshableAt.
	CASRefreshableAt(old, new int64) bool
	// SetRefreshableAt returns the refresh time.
	SetRefreshableAt(new int64)
	IsFresh(now int64) bool
	// Weight returns the weight of the node.
	Weight() uint32
	// SetWeight atomically replaces the weight (used for in-place updates).
	SetWeight(weight uint32)
	// PolicyWeight returns the weight the eviction policy has accounted for the node.
	PolicyWeight() uint32
	// SetPolicyWeight sets the weight the eviction policy has accounted for the node.
	SetPolicyWeight(weight uint32)
	// IsAlive returns true if the entry is available in the hash-table and page replacement policy.
	IsAlive() bool
	// IsRetired returns true if the entry was removed from the hash-table and is awaiting removal from the page
	// replacement policy.
	IsRetired() bool
	// Retire sets the node to the retired state.
	Retire()
	// IsDead returns true if the entry was removed from the hash-table and the page replacement policy.
	IsDead() bool
	// Die sets the node to the dead state.
	Die()
	// GetQueueType returns the queue that the entry's resides in (window, probation, or protected).
	GetQueueType() uint8
	// SetQueueType sets queue that the entry resides in (window, probation, or protected).
	SetQueueType(queueType uint8)
	// InWindow returns true if the entry is in the Window or Main space.
	InWindow() bool
	// MakeWindow sets the status to the Window queue.
	MakeWindow()
	// InMainProbation returns true if the entry is in the Main space's probation queue.
	InMainProbation() bool
	// MakeMainProbation sets the status to the Main space's probation queue.
	MakeMainProbation()
	// InMainProtected returns if the entry is in the Main space's protected queue.
	InMainProtected() bool
	// MakeMainProtected sets the status to the Main space's protected queue.
	MakeMainProtected()
}

func Equals[K comparable, V any](a, b Node[K, V]) bool {
	if a == nil {
		return b == nil || b.AsPointer() == nil
	}
	if b == nil {
		return a.AsPointer() == nil
	}
	return a.AsPointer() == b.AsPointer()
}

type Config struct {
	WithSize       bool
	WithExpiration bool
	WithWeight     bool
	WithRefresh    bool
}

type Manager[K comparable, V any] struct {
	create      func(key K, value V, expiresAt, refreshableAt int64, weight uint32) Node[K, V]
	fromPointer func(ptr unsafe.Pointer) Node[K, V]
}

func NewManager[K comparable, V any](c Config) *Manager[K, V] {
	var sb strings.Builder
	sb.WriteString("b")
	if c.WithSize {
		sb.WriteString("s")
	}
	if c.WithExpiration {
		sb.WriteString("e")
	}
	if c.WithRefresh {
		sb.WriteString("r")
	}
	if c.WithWeight {
		sb.WriteString("w")
	}
	nodeType := sb.String()
	if {{hasState}} {
		nodeType += valueStorage(reflect.TypeFor[V]())
	}
	m := &Manager[K, V]{}
`

	const nodeFooter = `return m
}

func (m *Manager[K, V]) Create(key K, value V, expiresAt, refreshableAt int64, weight uint32) Node[K, V] {
	return m.create(key, value, expiresAt, refreshableAt, weight)
}

func (m *Manager[K, V]) FromPointer(ptr unsafe.Pointer) Node[K, V] {
	return m.fromPointer(ptr)
}

func (m *Manager[K, V]) IsNil(n Node[K, V]) bool {
	return n == nil || n.AsPointer() == nil
}

// valueStorage returns the suffix of the node types that keep values of type t: a
// pointer-shaped value, or a value without pointers of up to 8 bytes, fits in one atomic word
// and is updated in place without a box.
func valueStorage(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer, reflect.Map, reflect.Chan, reflect.Func, reflect.UnsafePointer:
		return {{pointerStorage}}
	}
	if t.Size() <= 8 && !hasPointers(t) {
		return {{wordStorage}}
	}
	return {{inlineStorage}}
}

func hasPointers(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr,
		reflect.Float32, reflect.Float64, reflect.Complex64, reflect.Complex128:
		return false
	case reflect.Array:
		return t.Len() > 0 && hasPointers(t.Elem())
	case reflect.Struct:
		for i := range t.NumField() {
			if hasPointers(t.Field(i).Type) {
				return true
			}
		}
		return false
	default:
		return true
	}
}
`
	w := newWriter()

	// the storage suffixes and the rule for which nodes have state come from the generator, so
	// that NewManager builds exactly the node types that were generated
	stateConditions := make([]string, 0, len(stateFeatures))
	for _, f := range stateFeatures {
		//nolint:staticcheck // used only for ascii
		stateConditions = append(stateConditions, "c.With"+strings.Title(f.name))
	}
	template := strings.NewReplacer(
		"{{hasState}}", strings.Join(stateConditions, " || "),
		"{{pointerStorage}}", fmt.Sprintf("%q", pointerStorage),
		"{{wordStorage}}", fmt.Sprintf("%q", wordStorage),
		"{{inlineStorage}}", fmt.Sprintf("%q", inlineStorage),
	)

	w.p(template.Replace(nodeManager))
	w.in()
	w.p("switch nodeType {")
	for _, nodeType := range nodeTypes {
		for _, storage := range storagesOf(nodeType) {
			w.p("case \"%s\":", nodeType+storage)
			w.in()
			structName := structNameOf(nodeType, storage)
			w.p("m.create = New%s[K, V]", structName)
			w.p("m.fromPointer = CastPointerTo%s[K, V]", structName)
			w.out()
		}
	}
	w.p("default:")
	w.in()
	w.p("panic(\"not valid nodeType\")")
	w.out()
	w.p("}")
	w.p(template.Replace(nodeFooter))

	managerPath := filepath.Join(dir, "manager.go")
	f, err := os.Create(managerPath)
	if err != nil {
		return fmt.Errorf("create file %s: %w", managerPath, err)
	}
	defer f.Close()

	if _, err := f.Write(w.output()); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	return nil
}
