// Copyright (c) 2024 Alexey Mayshev and contributors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func printManager(dir string) error {
	const nodeManager = `// Code generated by NodeGenerator. DO NOT EDIT.

// Package node is a generated generator package.
package node

import (
	"reflect"
	"strings"
	"unsafe"
)

const (
	InWindowQueue uint8 = iota
	InMainProbationQueue
	InMainProtectedQueue
)

const (
	aliveState uint32 = iota
	retiredState
	deadState
)

// The layouts a node with state is allocated as, recorded in its header.
const (
{{variants}})

// Node is a cache entry.
type Node[K comparable, V any] interface {
	// Key returns the key.
	Key() K
	// Value returns the value.
	Value() V
	// SetValue replaces the value. It may be called on a node that is already in the cache only
	// when CanSetValue reports true, which makes it an atomic replacement that lock-free readers
	// never observe torn.
	SetValue(v V)
	// CanSetValue reports whether the value can be replaced in place with SetValue without a
	// concurrent reader observing a torn value: it is kept in one atomic word, or behind a pointer.
	CanSetValue() bool
	// AsPointer returns the node as a pointer.
	AsPointer() unsafe.Pointer
	// Prev returns the previous node in the eviction policy.
	Prev() Node[K, V]
	// SetPrev sets the previous node in the eviction policy.
	SetPrev(v Node[K, V])
	// Next returns the next node in the eviction policy.
	Next() Node[K, V]
	// SetNext sets the next node in the eviction policy.
	SetNext(v Node[K, V])
	// PrevExp returns the previous node in the expiration policy.
	PrevExp() Node[K, V]
	// SetPrevExp sets the previous node in the expiration policy.
	SetPrevExp(v Node[K, V])
	// NextExp returns the next node in the expiration policy.
	NextExp() Node[K, V]
	// SetNextExp sets the next node in the expiration policy.
	SetNextExp(v Node[K, V])
	// HasExpired returns true if node has expired.
	HasExpired(now int64) bool
	// ExpiresAt returns the expiration time.
	ExpiresAt() int64
	// CASExpiresAt executes the compare-and-swap operation for expiresAt.
	CASExpiresAt(old, new int64) bool
	// SetExpiresAt sets the expiration time.
	SetExpiresAt(new int64)
	// RefreshableAt returns the refresh time.
	RefreshableAt() int64
	// CASRefreshableAt executes the compare-and-swap operation for refreshableAt.
	CASRefreshableAt(old, new int64) bool
	// SetRefreshableAt returns the refresh time.
	SetRefreshableAt(new int64)
	IsFresh(now int64) bool
	// Weight returns the weight of the node.
	Weight() uint32
	// SetWeight atomically replaces the weight (used for in-place updates).
	SetWeight(weight uint32)
	// PolicyWeight returns the weight the eviction policy has accounted for the node.
	PolicyWeight() uint32
	// SetPolicyWeight sets the weight the eviction policy has accounted for the node.
	SetPolicyWeight(weight uint32)
	// IsAlive returns true if the entry is available in the hash-table and page replacement policy.
	IsAlive() bool
	// IsRetired returns true if the entry was removed from the hash-table and is awaiting removal from the page
	// replacement policy.
	IsRetired() bool
	// Retire sets the node to the retired state.
	Retire()
	// IsDead returns true if the entry was removed from the hash-table and the page replacement policy.
	IsDead() bool
	// Die sets the node to the dead state.
	Die()
	// GetQueueType returns the queue that the entry's resides in (window, probation, or protected).
	GetQueueType() uint8
	// SetQueueType sets queue that the entry resides in (window, probation, or protected).
	SetQueueType(queueType uint8)
	// InWindow returns true if the entry is in the Window or Main space.
	InWindow() bool
	// MakeWindow sets the status to the Window queue.
	MakeWindow()
	// InMainProbation returns true if the entry is in the Main space's probation queue.
	InMainProbation() bool
	// MakeMainProbation sets the status to the Main space's probation queue.
	MakeMainProbation()
	// InMainProtected returns if the entry is in the Main space's protected queue.
	InMainProtected() bool
	// MakeMainProtected sets the status to the Main space's protected queue.
	MakeMainProtected()
}

type Config struct {
	WithSize       bool
	WithExpiration bool
	WithWeight     bool
	WithRefresh    bool
}

type Manager[K comparable, V any] struct {
	create           func(key K, value V, expiresAt, refreshableAt int64, weight uint32, variant uint8) Node[K, V]
	fromPointer      func(ptr unsafe.Pointer) Node[K, V]
	valueStorage     string
	createdVariant   uint8
	updatableVariant uint8
}

func NewManager[K comparable, V any](c Config) *Manager[K, V] {
	var sb strings.Builder
	sb.WriteString("b")
	if c.WithSize {
		sb.WriteString("s")
	}
	if c.WithExpiration {
		sb.WriteString("e")
	}
	if c.WithRefresh {
		sb.WriteString("r")
	}
	if c.WithWeight {
		sb.WriteString("w")
	}
	nodeType := sb.String()
	m := &Manager[K, V]{}
	if {{hasState}} {
		m.valueStorage = valueStorage(reflect.TypeFor[V]())
		m.createdVariant, m.updatableVariant = variantsOfStorage(m.valueStorage)
	}
`

	const nodeFooter = `return m
}

func (m *Manager[K, V]) Create(key K, value V, expiresAt, refreshableAt int64, weight uint32) Node[K, V] {
	return m.create(key, value, expiresAt, refreshableAt, weight, m.createdVariant)
}

// CreateUpdatable creates a node whose value can be replaced in place (see Node.CanSetValue): a
// value that would be kept inline is kept behind an atomic pointer instead. Nodes without state
// are never updated in place and are created as by Create.
func (m *Manager[K, V]) CreateUpdatable(key K, value V, expiresAt, refreshableAt int64, weight uint32) Node[K, V] {
	return m.create(key, value, expiresAt, refreshableAt, weight, m.updatableVariant)
}

// ValueStorage returns how the nodes keep their values: "p" in an atomic pointer, "u64" in an
// atomic.Uint64, "empty" not at all (a value of zero size), or "" inline until the first update
// and behind an atomic pointer afterwards.
func (m *Manager[K, V]) ValueStorage() string {
	return m.valueStorage
}

func (m *Manager[K, V]) FromPointer(ptr unsafe.Pointer) Node[K, V] {
	return m.fromPointer(ptr)
}

// variantsOfStorage returns the layouts of the nodes of a value storage: the one a new entry is
// created as, and the one an entry whose value is replaced in place needs.
func variantsOfStorage(storage string) (created, updatable uint8) {
	switch storage {
	case {{pointerStorage}}:
		return pointerVariant, pointerVariant
	case {{wordStorage}}:
		return wordVariant, wordVariant
	case {{emptyStorage}}:
		return emptyVariant, emptyVariant
	default:
		return inlineVariant, boxedVariant
	}
}

// valueStorage returns how values of type t are kept: a pointer-shaped value, or a value
// without pointers of up to 8 bytes, fits in one atomic word and is updated in place without a
// box; a value of zero size is not stored at all.
func valueStorage(t reflect.Type) string {
	if t.Size() == 0 {
		return {{emptyStorage}}
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Map, reflect.Chan, reflect.Func, reflect.UnsafePointer:
		return {{pointerStorage}}
	}
	if t.Size() <= 8 && !hasPointers(t) {
		return {{wordStorage}}
	}
	return {{inlineStorage}}
}

func hasPointers(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Bool,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr,
		reflect.Float32, reflect.Float64, reflect.Complex64, reflect.Complex128:
		return false
	case reflect.Array:
		return t.Len() > 0 && hasPointers(t.Elem())
	case reflect.Struct:
		for i := range t.NumField() {
			if hasPointers(t.Field(i).Type) {
				return true
			}
		}
		return false
	default:
		return true
	}
}
`
	w := newWriter()

	// the storage suffixes and the rule for which nodes have state come from the generator, so
	// that NewManager builds exactly the node types that were generated
	stateConditions := make([]string, 0, len(stateFeatures))
	for _, f := range stateFeatures {
		//nolint:staticcheck // used only for ascii
		stateConditions = append(stateConditions, "c.With"+strings.Title(f.name))
	}
	var variants strings.Builder
	for i, v := range allVariants {
		if i == 0 {
			fmt.Fprintf(&variants, "\t%s uint8 = iota\n", v.constant)
		} else {
			fmt.Fprintf(&variants, "\t%s\n", v.constant)
		}
	}
	template := strings.NewReplacer(
		"{{variants}}", variants.String(),
		"{{hasState}}", strings.Join(stateConditions, " || "),
		"{{pointerStorage}}", fmt.Sprintf("%q", pointerStorage),
		"{{wordStorage}}", fmt.Sprintf("%q", wordStorage),
		"{{emptyStorage}}", fmt.Sprintf("%q", emptyStorage),
		"{{inlineStorage}}", fmt.Sprintf("%q", inlineStorage),
	)

	w.p(template.Replace(nodeManager))
	w.in()
	w.p("switch nodeType {")
	for _, nodeType := range nodeTypes {
		w.p("case \"%s\":", nodeType)
		w.in()
		typeName := typeNameOf(nodeType)
		w.p("m.create = New%s[K, V]", typeName)
		w.p("m.fromPointer = CastPointerTo%s[K, V]", typeName)
		w.out()
	}
	w.p("default:")
	w.in()
	w.p("panic(\"not valid nodeType\")")
	w.out()
	w.p("}")
	w.p(template.Replace(nodeFooter))

	managerPath := filepath.Join(dir, "manager.go")
	f, err := os.Create(managerPath)
	if err != nil {
		return fmt.Errorf("create file %s: %w", managerPath, err)
	}
	defer f.Close()

	if _, err := f.Write(w.output()); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	return nil
}
